### ISSUE TITLE
Learning together

### ISSUE THREAD

**Issue by LinXiaoTao** [PleaseCallMeCoder/PrettyGirls#1]
Hi~ I read your project, the project is still feeling a bit shabby on the current terms
For example, Fragment caching, local data source cache. These should not add it
I recommend a project using MVP mode
https://github.com/googlesamples/android-architecture/tree/todo-mvp
Learning together

**Comment by PleaseCallMeCoder** [comment]
Hello~Thanks for your comment.I know the problems in this project,but this is just a start.I will continue to improve it.I will learn the project that you recommend.I am a rookie,so,later please advise.Learning together.0.0

**Comment by ysmintor** [comment]
What I feel? you just can take a look of this address, which I think they have solved many problem.

https://github.com/konmik/nucleus
