### ISSUE TITLE
图片延迟淡入效果是如何实现的？

### ISSUE THREAD

**Issue by protectedMan** [PleaseCallMeCoder/PrettyGirls#10]
如题

**Comment by androidZgb** [comment]
我记得貌似是Glide实现的效果，题主可以试试翻翻相关资料。

**Comment by protectedMan** [comment]
我怀疑是Glide，但是找了，Glide没有使用淡入淡出效果啊

**Comment by Gentleman-jun** [comment]
Glide默认拥有这种效果的................

**Comment by PleaseCallMeCoder** [comment]
Glide默认是有淡入淡出效果的，需要修改的话可以通过crossFade()方法来操作。

**Comment by PleaseCallMeCoder** [comment]
Glide默认是有淡入淡出效果的，需要修改的话可以通过crossFade()方法来操作。
