### ISSUE TITLE
关于simpleBaseAdapter中的刷新数据方法

### ISSUE THREAD

**Issue by eaglewangl** [PleaseCallMeCoder/PrettyGirls#2]
能否通过先清空原有数据，然后通过list.addall(list)这样实现，直接this.list = list会不会存在异常？

**Comment by PleaseCallMeCoder** [comment]
你好，这个我个人认为是不会抛异常的，这样相当于把这个引用指向了内存中的新数据，没有可抛异常的地方吧。0.0

**Comment by mac090705** [comment]
list指向不变的情况下，调用`notifyDataSetChanged()`才会触发列表重新绘制并更新吧，如果给list重新赋值的话，应该是没有效果的。感觉更新数据的正确姿势应该是先`remove()`，再`add()`吧

**Comment by PleaseCallMeCoder** [comment]
fix 
修改为先清除数据，再添加
