### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by BelongsH** [PleaseCallMeCoder/PrettyGirls#3]
Thanks you project.

I found same problems.
1. why SplashActivity must new Fragment() ? I thinks activity can finish show splash task.
2.  Bitmap bitmap = BitmapUtil.drawableToBitmap(imageView.getDrawable());  has NullPointerException.

**Comment by VeerHan** [comment]
I have the same problem:
 "BitmapUtil.drawableToBitmap(imageView.getDrawable()); has NullPointerException."
