### ISSUE TITLE
关闭activity 栈管理ActivityManager.getInstance().finishActivity

### ISSUE THREAD

**Issue by fade0706** [PleaseCallMeCoder/PrettyGirls#6]
你好,最近在使用学习PrettyGirls这个项目,在学习基类的时候发现在AppActivity中的onDestroy方法中去调用 ActivityManager.getInstance().finishActivity(this);而当调用finish()的时候系统只是将栈最上层的activity移出栈,并没有及时去调用onDestroy也就是说我们自己维护的activity管理站类ActivityManager并没有及时的去从自己的栈里将这个activity移除,我在想在这里是不是在finish方法里调用ActivityManager.getInstance().finishActivity(this)会好点.

**Comment by PleaseCallMeCoder** [comment]
你好，个人认为如果你的Activity中不存在内存泄漏的话，调用完finish会继续调用onDestroy的，不会不及时0.0
