### ISSUE TITLE
mylibrary 是自己写的项目么 

### ISSUE THREAD

**Issue by caineyang** [PleaseCallMeCoder/PrettyGirls#8]
我是新学安卓的请问为什么里面的baseactivity要单独放在一个项目然后倒入不直接写在prettygirls项目里面，谢谢

**Comment by PleaseCallMeCoder** [comment]
你好，baselibrary中放的是每个项目里通用的东西，放到一个library里是为了可以在不同的项目里复用，方便其他项目的搭建。
